FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install Python dependencies
COPY requirements.prod.txt /app/
RUN pip install --no-cache-dir -r requirements.prod.txt

# Start SSH and FastAPI (using uvicorn)
CMD uvicorn main:app --host 0.0.0.0 --port 8000