# Use the PyTorch base image
FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime

# Install SSH server and other necessary packages
RUN apt-get update && apt-get install -y openssh-server build-essential libpython3-dev git
RUN mkdir /var/run/sshd

# Remove root password
RUN passwd -d root

# Configure SSH to permit root login without password
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config

# Expose the SSH port
EXPOSE 22

# Set the working directory in the container
WORKDIR /app

# Install packages specified in requirements.dev.txt
COPY requirements.dev.txt /app/
RUN pip install --no-cache-dir -r requirements.dev.txt

# Get the environment variables
ARG DATABASE_URL

RUN echo "DATABASE_URL=${DATABASE_URL}" >> /etc/environment

# Make conda available without running source command
RUN echo "source /opt/conda/etc/profile.d/conda.sh" >> /root/.bashrc

# Set up automatic cd to /app, activate conda, and set PYTHONPATH on login
RUN echo "cd /app" >> /root/.bashrc
RUN echo "conda activate" >> /root/.bashrc
RUN echo "export PYTHONPATH=/app:\$PYTHONPATH" >> /root/.bashrc

# Server is not running by default
# Start debugging server via SSH at debug_server.py, default port 8001
CMD service ssh start && sleep infinity
